name: PR build
on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'
      - uses: actions/checkout@v2
      - name: Test and build packages
        run: |-
          go vet ./...
          test -z $(gofmt -l -s .)
          go build -o /tmp/eve-cli .
